# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Om' do

platform :ios, '6.1'
pod 'KSToastView', '0.5.6'
pod 'THCalendarDatePicker', '~> 1.2.5'

pod 'DIDatepicker'
pod 'MMDrawerController', '~> 0.5.7'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0'
pod 'HanekeSwift'
pod 'MMMaterialDesignSpinner'

end

target 'OmTests' do

end

target 'OmUITests' do

end

