# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Om' do
pod 'MMDrawerController', '~> 0.5.7'
platform :ios, '6.1'
pod 'THCalendarDatePicker', '~> 1.2.5'
pod 'DIDatepicker'
end

target 'OmTests' do

end

target 'OmUITests' do

end

